name: meowtrack
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_local_notifications: 18.0.1
  audioplayers: ^4.1.0
  lottie: ^2.0.0
  timezone: ^0.9.2
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  http: ^0.13.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/cat_intro_animation.json
    - assets/animations/dashboard_animation.json
    - assets/animations/feeding_animation.json
    - assets/animations/water_animation.json
    - assets/animations/musics_animation.json
    - assets/music/Happy.mp3
    - assets/music/Playful.mp3
    - assets/music/Sleepy.mp3
    - assets/music/Relaxed.mp3